version: "2"
services:
  notifications:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres


  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - './data/db:/var/lib/postgresql/data'

