"""empty message

Revision ID: 198dda26c0d5
Revises: 
Create Date: 2019-02-12 20:35:24.107233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198dda26c0d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=True),
    sa.Column('lname', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('favourite_templates', sa.String(length=100), nullable=True),
    sa.Column('recepients', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
